/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JsonFormatterRouteImport } from './routes/json-formatter'
import { Route as ImageToPdfRouteImport } from './routes/image-to-pdf'
import { Route as ImageToBase64RouteImport } from './routes/image-to-base64'
import { Route as ImageFormatConverterRouteImport } from './routes/image-format-converter'
import { Route as ImageCropperRouteImport } from './routes/image-cropper'
import { Route as ImageCompressorRouteImport } from './routes/image-compressor'
import { Route as IndexRouteImport } from './routes/index'

const JsonFormatterRoute = JsonFormatterRouteImport.update({
  id: '/json-formatter',
  path: '/json-formatter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToPdfRoute = ImageToPdfRouteImport.update({
  id: '/image-to-pdf',
  path: '/image-to-pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageToBase64Route = ImageToBase64RouteImport.update({
  id: '/image-to-base64',
  path: '/image-to-base64',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageFormatConverterRoute = ImageFormatConverterRouteImport.update({
  id: '/image-format-converter',
  path: '/image-format-converter',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCropperRoute = ImageCropperRouteImport.update({
  id: '/image-cropper',
  path: '/image-cropper',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageCompressorRoute = ImageCompressorRouteImport.update({
  id: '/image-compressor',
  path: '/image-compressor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-cropper': typeof ImageCropperRoute
  '/image-format-converter': typeof ImageFormatConverterRoute
  '/image-to-base64': typeof ImageToBase64Route
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-cropper': typeof ImageCropperRoute
  '/image-format-converter': typeof ImageFormatConverterRoute
  '/image-to-base64': typeof ImageToBase64Route
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/image-compressor': typeof ImageCompressorRoute
  '/image-cropper': typeof ImageCropperRoute
  '/image-format-converter': typeof ImageFormatConverterRoute
  '/image-to-base64': typeof ImageToBase64Route
  '/image-to-pdf': typeof ImageToPdfRoute
  '/json-formatter': typeof JsonFormatterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/image-compressor'
    | '/image-cropper'
    | '/image-format-converter'
    | '/image-to-base64'
    | '/image-to-pdf'
    | '/json-formatter'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/image-compressor'
    | '/image-cropper'
    | '/image-format-converter'
    | '/image-to-base64'
    | '/image-to-pdf'
    | '/json-formatter'
  id:
    | '__root__'
    | '/'
    | '/image-compressor'
    | '/image-cropper'
    | '/image-format-converter'
    | '/image-to-base64'
    | '/image-to-pdf'
    | '/json-formatter'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImageCompressorRoute: typeof ImageCompressorRoute
  ImageCropperRoute: typeof ImageCropperRoute
  ImageFormatConverterRoute: typeof ImageFormatConverterRoute
  ImageToBase64Route: typeof ImageToBase64Route
  ImageToPdfRoute: typeof ImageToPdfRoute
  JsonFormatterRoute: typeof JsonFormatterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/json-formatter': {
      id: '/json-formatter'
      path: '/json-formatter'
      fullPath: '/json-formatter'
      preLoaderRoute: typeof JsonFormatterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-pdf': {
      id: '/image-to-pdf'
      path: '/image-to-pdf'
      fullPath: '/image-to-pdf'
      preLoaderRoute: typeof ImageToPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-to-base64': {
      id: '/image-to-base64'
      path: '/image-to-base64'
      fullPath: '/image-to-base64'
      preLoaderRoute: typeof ImageToBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-format-converter': {
      id: '/image-format-converter'
      path: '/image-format-converter'
      fullPath: '/image-format-converter'
      preLoaderRoute: typeof ImageFormatConverterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-cropper': {
      id: '/image-cropper'
      path: '/image-cropper'
      fullPath: '/image-cropper'
      preLoaderRoute: typeof ImageCropperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-compressor': {
      id: '/image-compressor'
      path: '/image-compressor'
      fullPath: '/image-compressor'
      preLoaderRoute: typeof ImageCompressorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImageCompressorRoute: ImageCompressorRoute,
  ImageCropperRoute: ImageCropperRoute,
  ImageFormatConverterRoute: ImageFormatConverterRoute,
  ImageToBase64Route: ImageToBase64Route,
  ImageToPdfRoute: ImageToPdfRoute,
  JsonFormatterRoute: JsonFormatterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
